version: '3.9'

services:
  api:
    container_name: api
    build: 
      context: ./api 
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    # environment:
    #   - DB_HOST=db
    #   - DB_PASSWORD=1234
    #   - DB=teste_fullstack
    #   - DB_USER=cayo
    #   - SECRET_KEY=S3CR3T_K3Y
    depends_on:
      db:
        condition: service_healthy

  client: 
   stdin_open: true
   build:
     context: ./app
     dockerfile: Dockerfile
   ports:
      - 3000:3000

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=cayo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=teste_fullstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cayo -d teste_fullstack"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

